# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Plantare' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for Aqui

pod 'GoogleMaps'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Firebase/Crash'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

end
